# Docker Compose — Multi-container orchestration
# Run: docker compose up --build
# Docs: https://docs.docker.com/compose/

services:
  #  # ─── Frontend ────────────────────────────────────
  #  frontend:
  #    build: ./frontend
  #    ports:
  #      - "${FRONTEND_PORT:-3000}:3000"
  #    depends_on:
  #      - gateway
  #    networks:
  #      - app-network
  #
    # ─── API Gateway ─────────────────────────────────
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "${GATEWAY_PORT:-8000}:8000"
    depends_on:
      - iam-service
    environment:
      - IAM_SERVICE_URL=http://iam-service:8085
      - ATTENDANCE_SERVICE_URL=http://attendance-service:8086
      - JWT_SECRET=${JWT_SECRET:-my_super_secret_jwt_key_12345}
    networks:
      - app-network

  # ─── IAM Service ─────────────────────────────────
  iam-service:
    build: ./services/iam-service
    container_name: iam-service
    ports:
      - "${IAM_SERVICE_PORT:-8085}:8085"
    depends_on:
      - iam-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iam-db:5432/${IAM_DB_NAME:-employee_db}
      - DB_USERNAME=${IAM_DB_USER:-postgres}
      - DB_PASSWORD=${IAM_DB_PASSWORD:-postgres}
      - JWT_SECRET=${JWT_SECRET:-my_super_secret_jwt_key_12345}
      - SPRING_SQL_INIT_MODE=always
    networks:
      - app-network

  # ─── Database for IAM ────────────────────────────
  iam-db:
    image: quay.io/debezium/postgres:16
    container_name: iam-db
    ports:
      - "${IAM_DB_PORT:-5434}:5432"
    environment:
      POSTGRES_DB: ${IAM_DB_NAME:-employee_db}
      POSTGRES_USER: ${IAM_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${IAM_DB_PASSWORD:-postgres}
    volumes:
      - iam-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # ─── Attendance Service ─────────────────────────────────
  attendance-service:
    build: ./services/attendance-service
    container_name: attendance-service
    ports:
      - "${ATTENDANCE_SERVICE_PORT:-8086}:8086"
    depends_on:
      - attendance-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://attendance-db:5432/${ATTENDANCE_DB_NAME:-attendance_db}
      - DB_USERNAME=${ATTENDANCE_DB_USER:-postgres}
      - DB_PASSWORD=${ATTENDANCE_DB_PASSWORD:-postgres}
      - SPRING_SQL_INIT_MODE=always
    networks:
      - app-network

  # ─── Database for IAM ────────────────────────────
  attendance-db:
    image: quay.io/debezium/postgres:16
    container_name: attendance-db
    ports:
      - "${ATTENDANCE_DB_PORT:-5435}:5432"
    environment:
      POSTGRES_DB: ${ATTENDANCE_DB_NAME:-attendance_db}
      POSTGRES_USER: ${ATTENDANCE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ATTENDANCE_DB_PASSWORD:-postgres}
    volumes:
      - attendance-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # ─── Event Service ────────────────────────────────
  event-service:
    build: ./services/event-service
    container_name: event-service
    ports:
      - "${EVENT_SERVICE_PORT:-8082}:8082"
    depends_on:
      event-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - DB_HOST=event-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-event_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - KAFKA_URL=kafka:29092
      - REGISTRATION_SERVICE_URL=http://registration-service:8083
    networks:
      - app-network

  # ─── Registration Service ─────────────────────────
  registration-service:
    build: ./services/registration-service
    container_name: registration-service
    ports:
      - "${REGISTRATION_SERVICE_PORT:-8083}:8083"
    depends_on:
      registration-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=registration-db
      - REGISTRATION_DB_PORT=5432
      - REGISTRATION_DB_NAME=${REGISTRATION_DB_NAME:-registration_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - KAFKA_URL=kafka:29092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  # ─── Payment Service ──────────────────────────────
  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT:-8084}:8084"
    depends_on:
      payment-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=payment-db
      - PAYMENT_DB_PORT=5432
      - PAYMENT_DB_NAME=${PAYMENT_DB_NAME:-payment_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - KAFKA_URL=kafka:29092
      - FRONTEND_PAYMENT_RESULT_URL=${FRONTEND_PAYMENT_RESULT_URL:-http://localhost:5173/payment/result}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL:-http://localhost:8084/api/v1/payments/vnpay-return}
      - VNPAY_IPN_URL=${VNPAY_IPN_URL:-http://localhost:8084/api/v1/payments/vnpay-ipn}
      - VNPAY_PAY_URL=${VNPAY_PAY_URL:-https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE:-2QX64648}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET:-RA4H94ZJ9K814W63255XY4S684352WVS}
    networks:
      - app-network

  # ─── Notification Service ─────────────────────────
  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-8088}:8087"
    depends_on:
      notification-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=notification-db
      - NOTIFICATION_DB_PORT=5432
      - NOTIFICATION_DB_NAME=${NOTIFICATION_DB_NAME:-notification_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - KAFKA_URL=kafka:29092
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - app-network

  # ─── Shared Infrastructure (Event DB) ────────────
  event-db:
    image: quay.io/debezium/postgres:16
    ports:
      - "${EVENT_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-event_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - event-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  registration-db:
    image: quay.io/debezium/postgres:16
    ports:
      - "${REGISTRATION_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${REGISTRATION_DB_NAME:-registration_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - registration_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  payment-db:
    image: quay.io/debezium/postgres:16
    ports:
      - "${PAYMENT_DB_PORT:-5434}:5432"
    environment:
      POSTGRES_DB: ${PAYMENT_DB_NAME:-payment_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  notification-db:
    image: quay.io/debezium/postgres:16
    ports:
      - "${NOTIFICATION_DB_PORT:-5437}:5432"
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME:-notification_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT:-2181}
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID:-1}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT:-2181}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_INTERNAL_PORT:-29092},PLAINTEXT_HOST://localhost:${KAFKA_PORT:-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  debezium:
    image: quay.io/debezium/connect:2.5
    ports:
      - "${DEBEZIUM_PORT:-8083}:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:${KAFKA_INTERNAL_PORT:-29092}
      GROUP_ID: ${DEBEZIUM_GROUP_ID:-1}

      CONFIG_STORAGE_TOPIC: ${DEBEZIUM_CONFIG_TOPIC:-my_connect_configs}
      OFFSET_STORAGE_TOPIC: ${DEBEZIUM_OFFSET_TOPIC:-my_connect_offsets}
      STATUS_STORAGE_TOPIC: ${DEBEZIUM_STATUS_TOPIC:-my_connect_statuses}
    depends_on:
      - kafka
      - event-db
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "${KAFKA_UI_PORT:-8080}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME:-local}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:${KAFKA_INTERNAL_PORT:-29092}
    depends_on:
      - kafka
    networks:
      - app-network

  debezium-init:
    image: curlimages/curl:latest
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-event_db}
      - DB_HOST=event-db
      - EVENT_DB_PORT=5432
      - DEBEZIUM_HOST=debezium
      - DEBEZIUM_PORT=8083
      - CONNECTOR_NAME=event-outbox-connector
      - TOPIC_PREFIX=vtit
      - TABLE_INCLUDE_LIST=public.outbox_events
      - ROUTE_TOPIC_REPLACEMENT=Event
    volumes:
      - ./scripts:/scripts:ro
    command: ["sh", "/scripts/debezium/register-connector.sh"]
    depends_on:
      - debezium
    restart: "no"
    networks:
      - app-network

  debezium-init-iam:
    image: curlimages/curl:latest
    environment:
      - DB_USER=${IAM_DB_USER:-postgres}
      - DB_PASSWORD=${IAM_DB_PASSWORD:-postgres}
      - DB_NAME=${IAM_DB_NAME:-employee_db}
      - DB_HOST=iam-db
      - DB_PORT=5432
      - DEBEZIUM_HOST=debezium
      - DEBEZIUM_PORT=8083
      - CONNECTOR_NAME=iam-outbox-connector
      - TOPIC_PREFIX=vtit
      - TABLE_INCLUDE_LIST=public.outbox_events
      - ROUTE_TOPIC_REPLACEMENT=Iam
    volumes:
      - ./scripts:/scripts:ro
    command: [ "sh", "/scripts/debezium/register-iam-connector.sh" ]
    depends_on:
      - debezium
      - iam-db

  registration-debezium-init:
    image: curlimages/curl:latest
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${REGISTRATION_DB_NAME:-registration_db}
      - DB_HOST=registration-db
      - EVENT_DB_PORT=5432
      - DEBEZIUM_HOST=debezium
      - DEBEZIUM_PORT=8083
      - CONNECTOR_NAME=registration-outbox-connector
      - TOPIC_PREFIX=vtit
      - TABLE_INCLUDE_LIST=public.outbox_events
      - ROUTE_TOPIC_REPLACEMENT=Registration
    volumes:
      - ./scripts:/scripts:ro
    command: ["sh", "/scripts/debezium/register-connector.sh"]
    depends_on:
      - debezium
      - registration-db
    restart: "no"
    networks:
      - app-network

  debezium-init-attendance:
    image: curlimages/curl:latest
    environment:
      - DB_USER=${ATTENDANCE_DB_USER:-postgres}
      - DB_PASSWORD=${ATTENDANCE_DB_PASSWORD:-postgres}
      - DB_NAME=${ATTENDANCE_DB_NAME:-attendance_db}
      - DB_HOST=attendance-db
      - DB_PORT=5432
      - DEBEZIUM_HOST=debezium
      - DEBEZIUM_PORT=8083
      - CONNECTOR_NAME=attendance-outbox-connector
      - TOPIC_PREFIX=vtit
      - TABLE_INCLUDE_LIST=public.outbox_events
      - ROUTE_TOPIC_REPLACEMENT=Attendance
    volumes:
      - ./scripts:/scripts:ro
    command: [ "sh", "/scripts/debezium/register-attendance-connector.sh" ]
    depends_on:
      - debezium
      - attendance-db

  payment-debezium-init:
    image: curlimages/curl:latest
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${PAYMENT_DB_NAME:-payment_db}
      - DB_HOST=payment-db
      - EVENT_DB_PORT=5432
      - DEBEZIUM_HOST=debezium
      - DEBEZIUM_PORT=8083
      - CONNECTOR_NAME=payment-outbox-connector
      - TOPIC_PREFIX=vtit
      - TABLE_INCLUDE_LIST=public.outbox_events
      - ROUTE_TOPIC_REPLACEMENT=Payment
    volumes:
      - ./scripts:/scripts:ro
    command: ["sh", "/scripts/debezium/register-connector.sh"]
    depends_on:
      - debezium
      - payment-db
    restart: "no"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  event-db-data:
  iam-db-data:
  attendance-db-data:
  registration_db_data:
  payment_db_data:
  notification_db_data:
