spring.config.import=optional:file:.env[.properties]

server.port=8000
spring.application.name=gateway

# CORS Config
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET, POST, PUT, DELETE, OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*

# Route Public
spring.cloud.gateway.routes[0].id=iam-public
spring.cloud.gateway.routes[0].uri=${IAM_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.routes[0].predicates[0]=Path=/v1/auth/login, /v1/auth/refresh-token

# Route Secured
spring.cloud.gateway.routes[1].id=iam-secured
spring.cloud.gateway.routes[1].uri=${IAM_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.routes[1].predicates[0]=Path=/v1/auth/me, /v1/Employees/**, /v1/auth/logout
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter

# Route Event
spring.cloud.gateway.routes[2].id=event-service-route
spring.cloud.gateway.routes[2].uri=${EVENT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/v1/events/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter

jwt.secret=${JWT_SECRET}
