server:
  port: ${EVENT_SERVICE_PORT:8082}

spring:
  application:
    name: event-service

  # Cấu hình Database
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:event_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # Cấu hình JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Cấu hình Kafka
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      # Key ID chai nên dùng StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Value là JSON Object nên dùng JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Không tự động gán metadata về Type (Tên Class) vào JSON header
        spring.json.add.type.headers: false

  cloud:
    openfeign:
      client:
        config:
          registration-service:
            connectTimeout: 2000
            readTimeout: 3000

# Cấu hình Bien môi trường
services:
  registration:
    url: ${REGISTRATION_SERVICE_URL:http://localhost:8083}
# Cấu hình Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      registrationCB:
        registerHealthIndicator: true #Spring Actuator
        slidingWindowType: COUNT_BASED  # Đo dựa trên số lần gọi
        slidingWindowSize: 20              # ghi nhớ 20 req gần nhất
        minimumNumberOfCalls: 10           # >= 10 req mới tính % lỗi
        failureRateThreshold: 50           # Tỉ lệ lỗi > 50%
        slowCallRateThreshold: 50          # Tỉ lệ chậm > 50% cũng ngắt
        slowCallDurationThreshold: 2s      # call quá 2s coi như chậm
        waitDurationInOpenState: 10s       # 10s không gọi sang
        permittedNumberOfCallsInHalfOpenState: 3  # 3 req vào để thử -> nếu lỗi lại đóng lại 10s
        automaticTransitionFromOpenToHalfOpenEnabled: false # lưu mốc ngắt mạch khi nào có req tơi mới kiểm tra thời gian so với thời gian lưu mốc
        ignoreExceptions:
          - feign.FeignException$FeignClientException   # lỗi 4xx không tính là circuit breaker failure
  bulkhead:
    instances:
      registrationCB:
        maxConcurrentCalls: 15
        maxWaitDuration: 0ms
resilience4j.circuitbreaker.circuit-breaker-aspect-order: 1
resilience4j.bulkhead.bulkhead-aspect-order: 2

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers
