spring.config.import=optional:file:.env[.properties]

server.port=${IAM_SERVICE_PORT:8085}

spring.application.name=iam-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${IAM_DB_PORT:5432}/${IAM_DB_NAME:employee_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true

jwt.secret=${JWT_SECRET}
